### ISSUE TITLE
List of available jobs to be run

### ISSUE THREAD

**Issue by sabativi** [msavin/SteveJobs#100]
Hello,

I just want to do a small UI where I can run jobs definining server side, is there any way to get the list of all jobs that have been registered ?

Thanks

**Comment by msavin** [comment]
Yep you can just do a query to Jobs.collection

**Comment by sabativi** [comment]
But the first time, I have not run any job so there will be nothing inside Job Collection

When I do 

```
Jobs.register({
name1: function(){},
name2: function(){}
})
```

**Comment by msavin** [comment]
The job is only created when you run Jobs.run

**Comment by sabativi** [comment]
Yes I know that but when running Jobs.run(name) there must be a way to check that a job named "name" exists
So there must be somewhere where you have the list of all possible jobs to be runned
I do not want to know pending jobs, only list of jobs that can be run

Thanks again for your time

**Comment by sabativi** [comment]
Here is a way to do it 

```
import { Jobs, JobsInternal } from "meteor/msavin:sjobs";

new SecuredMethod({
  name: "Jobs.list",
  validate: () => {},
  run() {
    const manager = JobsInternal.Operator.manager;
    const jobs = Object.keys(manager.queues);
    return jobs;
  },
});
```
