### ISSUE TITLE
Jobs Stuck Pending on Galaxy

### ISSUE THREAD

**Issue by mvogttech** [msavin/SteveJobs#103]
I can see that jobs are being created in the 'jobs_data' collection.

But they never actually start.

**Comment by mvogttech** [comment]
Found the issue.

Had to do with the dominator collection when a new instance is launched.

Perhaps there should be a parameter in the config to clear the dominator collection on system startup.

**Comment by msavin** [comment]
That’s strange - it shouldn’t be an issue - works fine everywhere. 

It could take 5 minutes or so for Dominator to take control of a server - that is the grace period. Could that have been the problem?

**Comment by mvogttech** [comment]
Deleting the only document in the 'jobs-dominator' collection fixed the issue.
