### ISSUE TITLE
server/imports/utilities/collection/index.js --> Cannot read property 'parent' of null

### ISSUE THREAD

**Issue by jakecarlson** [msavin/SteveJobs#104]
Hello,

I upgraded from 4.3.0 to 4.3.1, and I am now getting the following error on startup when developing locally:

=> Errors prevented startup:                  
   
   While building for os.osx.x86_64:
   packages/msavin:sjobs/server/imports/utilities/collection/index.js:
   Cannot read property 'parent' of null

I am on the latest version of Meteor 2.7.3 and latest version of Node. My machine is MacOS 12.5.1, Intel. Can you please assist with further troubleshooting steps?

**Comment by StorytellerCZ** [comment]
Can confirm as well.

**Comment by msavin** [comment]
@jakecarlson @StorytellerCZ must be something that changed with new Meteor updates - fixed

**Comment by StorytellerCZ** [comment]
The latest patch version fixes the issue! Thank you @msavin !

**Comment by jakecarlson** [comment]
Works for me as well, thanks @msavin !
