### ISSUE TITLE
Prevent queue from stopping after failure

### ISSUE THREAD

**Issue by sabativi** [msavin/SteveJobs#105]
Hello, is there any way to prevent the queue from stopping after a certain job failed, I have a generic job which takes some params, and if one failed I do not want to queue to stop.

Thanks

**Comment by sabativi** [comment]
@msavin sorry to ping you, but I still have the problem with `{ singular: false }`, do you have any advice on this ?

**Comment by msavin** [comment]
hey @sabativi  if the job failed - it's most likely due to a code error and that should not happen. 

you can try this kind of pattern to avoid triggering the queue's error tracking mechanisms:

```
try {
    // run logic
} catch (e) {
    this.reschedule({...})
}
```

let me know if you have any other questions

**Comment by sabativi** [comment]
Thanks @msavin 

Yes but what if I want multiple jobs to be able to run in //, can I ?

**Comment by msavin** [comment]
Yep you can put any logic in between the try / catch statement. Sent from my iPhoneOn Dec 13, 2022, at 12:40 PM, Victor Sabatier ***@***.***> wrote:﻿
Thanks @msavin
Yes but what if I want multiple jobs to be able to run in //, can I ?

**Comment by sabativi** [comment]
I might have not explained my problem properly : here is the jobs_data collection :
<img width="1235" alt="Screenshot 2022-12-14 at 09 08 42" src="https://user-images.githubusercontent.com/2357779/207540954-b90de42a-b43d-4493-96b5-01addddbda73.png">

One job failed and prevent the following from working whereas they have differents arguments ( but same name ), so I want the jobs to run even if one previous failed

**Comment by msavin** [comment]
Are you setting the failure state manually?

The failure state is only intended for code failure.

If you are not getting the result you want or need to rerun the job, you
need to use this.reschedule()

**Comment by sabativi** [comment]
No I am not, I guess an error is thrown and not catch in my code 
Ok I will use the reschedule function 
Thanks for yours answers
