### ISSUE TITLE
Module not installed

### ISSUE THREAD

**Issue by ironmanromeo** [msavin/SteveJobs#70]
Hi msavin, thank you so much for what U do here. Meanwhile, I think to have a problem with SJ installation. I'm following, your instructions, but after a response from terminal that all is gone right, import { Jobs } from 'meteor/msavin:sjobs' return "undefined" and WebStorm return that "meteor/msavin:sjobs" module is not installed. I found in ".meteor/build/programs/server/app/global-imports.js" "Jobs = Package['msavin:sjobs'].Jobs;" so, I decide to remove the offendi import line. Result: SJ is running, but start with this message: "msavin:sjobs-ui-debugger : msavin:sjobs package not found or using old version", then on Jobs.run... "Jobs: Invalid input for undefined, obs: therefore, it was set to 0", and nothing in "ui-debugger". Despite this, process are all correctly fired. Meteor: last, react, last. With older version of Meteor, all was right. Can I address me to right way? Thx, Romeo

**Comment by msavin** [comment]
Do you have Meteor modules / ecmascript packages installed?

**Comment by msavin** [comment]
Closing on the assumption that you had moved past this issue. If anything comes up, please let me know.
