### ISSUE TITLE
Client side jobs

### ISSUE THREAD

**Issue by agustinjch** [msavin/SteveJobs#74]
I'm writing an admin view in my project to be able to see on going jobs (I know there is the GUI, but I need some stuff there for my project).

So I've been trying to do as it's written in the wiki here https://github.com/msavin/SteveJobs/wiki/Engineering , but it doesn't work creating the collection `jobs_data` , getting an error:

`Error: There is already a collection named "jobs_data"` 

I don't know if I'm doing something wrong, or basically it doesn't work that way.

**Comment by msavin** [comment]
Try to initialize the collection only on the client. If you are doing it in
a shared folder, you will get that error because the collection is already
initialized on the server.

**Comment by agustinjch** [comment]
Hello again. 

First, thanks for the fast reply!

I had it in a shared file but inside a `if (Meteor.isClient)` and I was getting that error.

I did as you said, and I'm still getting the same error.

If you need more info, let me know and I can paste here the files.

Thanks in advance

**Comment by msavin** [comment]
Hmm, that should do it. Do you have the debug package installed? That might
be causing the client side collection to be initialized

**Comment by agustinjch** [comment]
Hello again,

Found the problem, I had the blaze package `msavin:sjobs-ui-blaze` installed. I guess that in this package, the jobs_data collection is initialized to, that's why I was getting the error.

Thanks again!

Cheers
