### ISSUE TITLE
Sending a daily email at a specific time and taking into account timezones

### ISSUE THREAD

**Issue by jamauro** [msavin/SteveJobs#75]
Hi @msavin,

This looks like it could be a good fit for what I'm trying to accomplish, but I'm not exactly sure of the best way to go about it. I'm hoping you might be able to point me in the right direction.

**Here's what I'm trying to accomplish:**
Send an email everyday at 10am for every user who has the email digest turned on. So for someone in Chicago, they'd receive it at 10am CST and someone in New York would receive it at 10am EST.

**Comment by MrSpark2591** [comment]
Try this one:
https://github.com/Fasal-Tech/meteor-synced-cron
It's the fork that we are using for the timezone support.

**Comment by msavin** [comment]
hey @jamauro, this would require you to set the initial send at the desired time, and then you can run `this.reschedule({in: { hours: 24}})`.
