### ISSUE TITLE
Error is printed in console, but not saved in job 

### ISSUE THREAD

**Issue by gerwinbrunner** [msavin/SteveJobs#77]
https://github.com/msavin/SteveJobs/blob/521d70fae5c614a657ec21f1ff6e8ad5a97420e4/package/server/imports/actions/execute/process.js#L24-L26

The job is set to be a failure, but the exception and stack in not persisted.
It would be really nice if the stacktrace is not only logged to the console, but also to the Job failture.

Would that make sense to someone else?

**Comment by gerwinbrunner** [comment]
Just adding this will auto add the error:

```
 	var failure = Toolbelt.failure(e.stack); 
```

**Comment by msavin** [comment]
@gerwinbrunner good idea, can you PR it?

**Comment by msavin** [comment]
@gerwinbrunner error is now saved when a job fails
