### ISSUE TITLE
Update state to "running" when job is started

### ISSUE THREAD

**Issue by gerwinbrunner** [msavin/SteveJobs#78]
It would be really aweseome if a job would be set to "running" just before it is executed to see in the ui that this current job is beeing processed.

**Comment by msavin** [comment]
I thought about it, but I'm not sure that it would be worth the extra database write, especially as it can add a performance cost when running thousands of jobs

**Comment by msavin** [comment]
Here's what I'm thinking now:
 - `this.set` can be used to add a "running" flag 
 - automatically setting a running flag for each job is not worth it as it would add two database operations for each job that runs 
  - am open to being persuaded otherwise

**Comment by msavin** [comment]
Closing topic as it is stale / non-issue
