### ISSUE TITLE
Add Result for reschedule call

### ISSUE THREAD

**Issue by gerwinbrunner** [msavin/SteveJobs#79]
https://github.com/msavin/SteveJobs/blob/27cdf83a256a6c38a357cc442892c03955612b1f/package/server/imports/actions/reschedule/index.js#L16-L20

I think it would be good to have also the result field passed to the reschedule call and then pushed that to the history.

**Comment by msavin** [comment]
@gerwinbrunner good idea, can you PR it?

**Comment by msavin** [comment]
@gerwinbrunner on second thought, I think using `this.set` and `this.get` makes more sense. Seeing as how  there has been low engagement on this topic, I will close it. 

If you have a use case for it, would love to know
