### ISSUE TITLE
what if we deploy Meteor on multiple instances with load balancing?

### ISSUE THREAD

**Issue by minhna** [msavin/SteveJobs#80]
I've not tried yet, but I think jobs may get duplicated.
Do you have any plan/idea for this situation?
Thank you.

**Comment by msavin** [comment]
hey @minhna, the package works only on server at a time

**Comment by msavin** [comment]
check out the `dominator` functions in `operator` folder to see how that works

**Comment by minhna** [comment]
Thank you very much.
