### ISSUE TITLE
Jobs.find not part of Atmosphere package

### ISSUE THREAD

**Issue by ShaggyKris** [msavin/SteveJobs#84]
Hi there. Found that Jobs.find() is in the documentation, but it doesn't appear to be in the current meteor package. Don't know if this is known or not.

**Comment by msavin** [comment]
The new version is not published yet, but you could find a tutorial online on how to run a local package. After a bit of testing, I will publish this version

**Comment by kratam** [comment]
+1. It would be great to mention this in the documentation.

**Comment by janat08** [comment]
I can't tell where the npm package is.

**Comment by msavin** [comment]
hey folks, v4.0 is finally up and this feature is part of it
