### ISSUE TITLE
Version 3 causing rendering issue on instagram browser on iPhone

### ISSUE THREAD

**Issue by mikeacre** [msavin/SteveJobs#88]
I will do some more research into this shortly, but currently with Meteor 1.10 and Steve jobs package 3.1.1 the app does not load at all on instagram browser on an iPhone.. reducing the package version to 1.0.1 works.

**Comment by msavin** [comment]
Can you provide more information? The core package has does not have an UI component.

**Comment by mikeacre** [comment]
I determined this was a different package causing this issue.
