### ISSUE TITLE
jobs are not run consecutively

### ISSUE THREAD

**Issue by JanMP** [msavin/SteveJobs#90]
I need jobs to make sure that some lengthy async functions (awaiting results before calling this.success) are run consecutively in the order Jobs.run was called. But I can't get it to work. I make no use of any timing features and all priorities are at default.

I start a lengthy job, the status is shown as  pending. 10ish seconds later I start a quick job (while job 1 is still pending) and it is quickly going to pending and then success. Then a couple minutes later job 1  is finally done and switching to success.

**Comment by JanMP** [comment]
ah ok, i think i get it. When I register a job it creates it's own que. Is there an elegant way to have different kinds of jobs que up in the same line (besides creating a job that then runs a switch statement to run different functions)?

**Comment by msavin** [comment]
Hey - thanks for using Steve Jobs!

Up until the new 4.0 (just published), the package did not support async functions, which is why the jobs ran all at once. It should be good to go now, please let me know if you run into any issues!
