### ISSUE TITLE
Jobs: Unable to execute job - queue is busy, randomly appearing.

### ISSUE THREAD

**Issue by Gorbus** [msavin/SteveJobs#93]
Hi @msavin,

We are using Jobs in production and generally everything works very fine. However once in a while we get the following message:

![image](https://user-images.githubusercontent.com/12472982/104915000-49029200-5990-11eb-9c0a-fce42d5da654.png)

And while it doesn't seem to block the other jobs this one can get stuck and affect our user experience. The appearance of the message seems very random to us. Therefore I'd like to know:

- What could be the cause of this message (previous job not over? this job can not finished ?)
- What's the consequences (it didn't seem to retrigger afterwards, shouldn't it ?)

Thanks in advance for your help. The registered job is the following:

```
Jobs.register({
  submitTeamAnswerJob: function (
    challengeId,
    isAdmin,
    teamId,
    sessionId,
    activityId
  ) {
    const activity = Activities.findOne({ _id: activityId });

    try {
      if (activity) {
        const { liveSessions } = activity;
        const session = liveSessions.find(({ _id }) => _id === sessionId);
        const { teams } = session;
        const team = teams.find(({ _id }) => _id === teamId);
        const { name } = team;
        submitTeamAnswer({
          challengeId,
          isAdmin,
          teamId,
          sessionId,
          teamName: name,
        });
      }
    } catch (e) {
      console.log(e);
    }

    this.success();
  },
});
```

I just added the try catch by security (could it help) ? But the error message happened before the try catch was set up. We didn't get any error regarding the submitTeamAnswer function when it was triggered.

**Comment by Gorbus** [comment]
It seems it may be appearing sometimes when we're trying to force the execution of the job before it was triggered using Jobs.execute

**Comment by msavin** [comment]
Hey @Gorbus  - sorry for the delay - but yes passing in the force function is the right thing to do. So long as you don't try to simultaneously force 1000 jobs to execute at the same time, should be ok :)

Please let me know if you have any other issues
